### ISSUE TITLE
Error `TypeError: wait() got an unexpected keyword argument 'loop'` 

### ISSUE THREAD

**Issue by def-mycroft** [Graeme22/tastyworks-cli#27]
When running `twcli option chain SPY` I receive `TypeError: wait() got an unexpected keyword argument 'loop'`. 

[Here](https://dpaste.com//3PKBAWAKM) is the full traceback. 

[Here](https://dpaste.com//3CALKHWHN) is the output of `pip freeze` in my environment. Python version 3.10.4. 

I am able to use `twcli plot` without error.

**Comment by def-mycroft** [comment]
not sure what else to provide.

**Comment by Graeme22** [comment]
Ah I know what it is, looks like the problem is Python 3.10 removed one of the keyword arguments, so I wasn't having problems because I'm still using an older Python!

Looks like using [this ](https://github.com/random-python/x_aiocometd/commit/cab6063f09ab30436473575ff1f693b6f71d459a) `aiocometd` fork will fix both this issue and the annoying error logging that is showing up!

I'll leave this open until I get the chance to implement that.

**Comment by Graeme22** [comment]
Hey @def-mycroft, could you see if #28 fixes the issue?

**Comment by def-mycroft** [comment]
hi @Graeme22 , I'm up and running now!! thanks for the fix :)
